import type { AgentLayer } from "@/types/agent-data";

export const VERSION_ORDER = [
  "s01",
  "s02",
  "s03",
  "s04",
  "s05",
  "s06",
  "s07",
  "s08",
  "s09",
  "s10",
  "s11",
  "s12",
  "s13",
  "s14",
  "s15",
  "s16",
  "s17",
  "s18",
  "s19",
  "s20",
  "s21",
  "s22",
  "s23",
] as const;

export const LEARNING_PATH = VERSION_ORDER;

export type VersionId = typeof LEARNING_PATH[number];

export const VERSION_META: Record<string, {
  title: string;
  subtitle: string;
  coreAddition: string;
  keyInsight: string;
  layer: AgentLayer;
  prevVersion: string | null;
}> = {
  s01: {
    title: "The Agent Loop",
    subtitle: "One Loop Is All You Need",
    coreAddition: "Minimal model/tool loop over the Responses API",
    keyInsight: "The smallest useful agent is a loop that calls the model, runs tools, and feeds results back.",
    layer: "tools",
    prevVersion: null,
  },
  s02: {
    title: "Tool Use",
    subtitle: "Structured Tools, Not Just a Shell",
    coreAddition: "Tool registry & dispatch map",
    keyInsight: "The loop stays stable while capabilities register into a dispatch table.",
    layer: "tools",
    prevVersion: "s01",
  },
  s03: {
    title: "Approval & Permissions",
    subtitle: "Ask Before You Act",
    coreAddition: "approval_policy gate",
    keyInsight: "Codex's approval modes (untrusted / on-failure / on-request / never) are a harness decision point before the shell runs.",
    layer: "tools",
    prevVersion: "s02",
  },
  s04: {
    title: "Sandbox",
    subtitle: "Run It, But Contain It",
    coreAddition: "sandbox_mode exec policy",
    keyInsight: "read-only / workspace-write / danger-full-access, backed by OS isolation, decides what a command can actually touch.",
    layer: "tools",
    prevVersion: "s03",
  },
  s05: {
    title: "The Plan Tool",
    subtitle: "An Agent Without a Plan Drifts",
    coreAddition: "update_plan todo manager",
    keyInsight: "Explicit plans keep long-running work visible and correctable — Codex exposes this as the update_plan tool.",
    layer: "planning",
    prevVersion: "s04",
  },
  s06: {
    title: "Subagents",
    subtitle: "Delegate With a Clean Context",
    coreAddition: "Isolated subtask delegation",
    keyInsight: "Subagents give each subtask a clean message history while preserving the main thread.",
    layer: "planning",
    prevVersion: "s05",
  },
  s07: {
    title: "Skills",
    subtitle: "Load Expertise Only When Needed",
    coreAddition: "On-demand skill loader",
    keyInsight: "Codex skills inject specialized instructions only when the task actually needs them.",
    layer: "planning",
    prevVersion: "s06",
  },
  s08: {
    title: "Context Compaction",
    subtitle: "Context Will Fill Up",
    coreAddition: "Auto-compaction",
    keyInsight: "Compaction keeps the conversation usable when the context window gets crowded.",
    layer: "memory",
    prevVersion: "s07",
  },
  s09: {
    title: "Memory & Sessions",
    subtitle: "Don't Lose the Details",
    coreAddition: "Rollout persistence & resume",
    keyInsight: "Session rollouts let codex resume survive restarts; some facts should outlive summarization.",
    layer: "memory",
    prevVersion: "s08",
  },
  s10: {
    title: "Instructions & AGENTS.md",
    subtitle: "Assembled at Runtime, Never Hardcoded",
    coreAddition: "Runtime instruction assembly",
    keyInsight: "The system prompt is a generated product of AGENTS.md, config.toml, profiles and built-ins.",
    layer: "planning",
    prevVersion: "s09",
  },
  s11: {
    title: "Error Recovery",
    subtitle: "Errors Are the Start of a Retry",
    coreAddition: "Classified retry strategy",
    keyInsight: "A robust harness classifies failures (rate limit, overflow, abort) and decides what kind of retry is worthwhile.",
    layer: "planning",
    prevVersion: "s10",
  },
  s12: {
    title: "Task System",
    subtitle: "Break Big Goals Into Small Tasks",
    coreAddition: "Shared task board",
    keyInsight: "A task graph turns vague goals into ordered, observable work.",
    layer: "collaboration",
    prevVersion: "s11",
  },
  s13: {
    title: "Background Tasks",
    subtitle: "Slow Work Goes to the Background",
    coreAddition: "Async background execution",
    keyInsight: "The agent keeps reasoning while slow commands finish elsewhere — codex exec taken further.",
    layer: "concurrency",
    prevVersion: "s12",
  },
  s14: {
    title: "Automations",
    subtitle: "Work on a Schedule",
    coreAddition: "Scheduled / triggered runs",
    keyInsight: "Recurring work should be created by the harness, not remembered by the model.",
    layer: "concurrency",
    prevVersion: "s13",
  },
  s15: {
    title: "Agent Teams",
    subtitle: "One Agent Isn't Enough, Form a Team",
    coreAddition: "Teammate mailboxes",
    keyInsight: "Persistent teammates let work continue in parallel without stuffing every thought into one context.",
    layer: "collaboration",
    prevVersion: "s14",
  },
  s16: {
    title: "Team Protocols",
    subtitle: "Teammates Need Agreements",
    coreAddition: "Shared coordination contracts",
    keyInsight: "Multi-agent systems need explicit message contracts, not vibes.",
    layer: "collaboration",
    prevVersion: "s15",
  },
  s17: {
    title: "Autonomous Agents",
    subtitle: "Check the Board, Claim the Task",
    coreAddition: "Autonomous task claiming",
    keyInsight: "Teammates become useful when they can discover and claim work themselves.",
    layer: "collaboration",
    prevVersion: "s16",
  },
  s18: {
    title: "Worktree Isolation",
    subtitle: "Separate Directories, No Conflicts",
    coreAddition: "Git worktree lifecycle",
    keyInsight: "Parallel agents need isolated filesystems as much as isolated conversations — the model Codex Cloud runs on.",
    layer: "collaboration",
    prevVersion: "s17",
  },
  s19: {
    title: "MCP Servers",
    subtitle: "External Tools, Standard Protocol",
    coreAddition: "MCP tool bridge",
    keyInsight: "External services become agent tools through a standard discovery and call protocol configured in config.toml.",
    layer: "collaboration",
    prevVersion: "s18",
  },
  s20: {
    title: "The Full Harness",
    subtitle: "All Mechanisms, One Loop",
    coreAddition: "Integrated harness",
    keyInsight: "The final harness is still one loop, now surrounded by the systems that make it production-shaped.",
    layer: "collaboration",
    prevVersion: "s19",
  },
  s21: {
    title: "The Codex CLI Surface",
    subtitle: "One Binary, Many Doors",
    coreAddition: "Command & slash-command dispatch",
    keyInsight: "codex exec/resume/review/login/mcp and the /slash commands are one dispatch layer over the same harness.",
    layer: "codex",
    prevVersion: "s20",
  },
  s22: {
    title: "config.toml in Depth",
    subtitle: "Every Knob, One Resolver",
    coreAddition: "Full config schema & precedence",
    keyInsight: "model_providers, wire_api, sandbox_workspace_write, profiles and mcp_servers all resolve through one precedence chain.",
    layer: "codex",
    prevVersion: "s21",
  },
  s23: {
    title: "Review, CI & Cloud",
    subtitle: "The Harness Leaves Your Laptop",
    coreAddition: "Review mode & headless runs",
    keyInsight: "codex review, codex exec in CI, and Codex Cloud tasks are the same loop running unattended on real work.",
    layer: "codex",
    prevVersion: "s22",
  },
};

export const LAYERS = [
  {
    id: "tools" as const,
    label: "Tools & Execution",
    color: "#3B82F6",
    versions: ["s01", "s02", "s03", "s04"],
  },
  {
    id: "planning" as const,
    label: "Planning & Control",
    color: "#10B981",
    versions: ["s05", "s06", "s07", "s10", "s11"],
  },
  {
    id: "memory" as const,
    label: "Memory Management",
    color: "#8B5CF6",
    versions: ["s08", "s09"],
  },
  {
    id: "concurrency" as const,
    label: "Concurrency & Automation",
    color: "#F59E0B",
    versions: ["s13", "s14"],
  },
  {
    id: "collaboration" as const,
    label: "Multi-Agent Platform",
    color: "#EF4444",
    versions: ["s12", "s15", "s16", "s17", "s18", "s19", "s20"],
  },
  {
    id: "codex" as const,
    label: "Codex in Depth",
    color: "#06B6D4",
    versions: ["s21", "s22", "s23"],
  },
] as const;
